steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/scheduler-service', 
      '--build-arg', 
      'BUILD_TIMESTAMP=${_BUILD_TIMESTAMP}',
      '--build-arg',
      'COMMIT_SHA=$COMMIT_SHA',
      '--build-arg',
      'DEPLOYMENT_ID=$BUILD_ID',
      '.'
    ]
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/scheduler-service']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scheduler-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/scheduler-service'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'scheduler-service@delta-entity-447812-p2.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production,BUILD_TIMESTAMP=${_BUILD_TIMESTAMP},COMMIT_SHA=$COMMIT_SHA,DEPLOYMENT_ID=$BUILD_ID'

substitutions:
  _BUILD_TIMESTAMP: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

images:
  - 'gcr.io/$PROJECT_ID/scheduler-service'